package com.ru.questiondiary.web.dto;

public enum ErrorCode {
    AUTHENTICATION_ERROR,
    COMMUNITY_NOT_FOUND,
    DUPLICATE_VOTE,
    DUPLICATE_QUESTION,
    QUESTION_NOT_FOUND,
    INVALID_TOKEN,
    DUPLICATE_EMAIL,
    USER_NOT_FOUND,
    BAD_CREDENTIALS
}
